#!/usr/bin/env bash

# Given a bounding box string of the format
#
#     {min_lon},{min_lat},{max_lon},{max_lat}
#
# emits a new bouding box string with the ordering changed
# to:
#
#     {min_lon},{max_lon},{min_lat},{max_lat}
#
# which is more useful for other tooling and scripts.

# Process bbox param into separate script vars.
IFS=, read -r min_lon min_lat max_lon max_lat <<<"${1}"

echo "Received ${1}"
echo "${min_lon},${max_lon},${min_lat},${max_lat}"
