#!/usr/bin/env bash

# Reads Gemini bookmarks file (at ~/.config/gemini/.gmimarks) and
# passes through fzf for selection

url=$(fzf --height=10 < ~/.config/gemini/.gmimarks | cut -d'|' -f2)

gmi $url
