#!/usr/bin/env bash

# Wrap gmiget to provide default searching of Gemini
# pages vis geminispace.info

for dep in gmiget gmifmt; do
    command -v "$dep" >/dev/null || echo "Missing '$dep'"
done

gmiget gemini://geminispace.info/search?"$1" | gmifmt -m 2
